Added code format check of `.proto` files
3rdparty/stout-grpc pull request #24
Opened 2021-09-30 18:55 UTC by ArthurBandaryk

Added `check_style_proto` in the `tools` directory. It's a simple bash script
which is run in the check_format_code.yaml action.

2021-09-30 18:56 UTC, ArthurBandaryk commented
Also tested `check_style_proto` script locally. Was playing with correct format, then added some format errors and made some lines exceed `80` characters. The results and `test.proto` file are on the screen below.
![Screen Shot 2021-09-30 at 9 40 15 PM](https://user-images.githubusercontent.com/68085133/135514337-3ac0d7bf-4122-4790-96e5-7c31cf455972.png)
![Screen Shot 2021-09-30 at 9 41 04 PM](https://user-images.githubusercontent.com/68085133/135514350-861ac54d-d099-43f0-83df-aab8010d61f5.png)
![Screen Shot 2021-09-30 at 9 41 37 PM](https://user-images.githubusercontent.com/68085133/135514356-80f41482-b73f-49dc-b34a-70bb981e04f1.png)

2021-09-30 22:03 UTC, while-false requested changes
Hey Arthur, thanks for executing on this! I like the setup with the shell script at the `prototools` linter. I'd like to `clang-format` to the mix.

`clang-format` can also be used to check and enforce protobuf files, and since we are already using it for C++ files, it is easy to expand the `.clang-format` file: all you'd need to add is a segment like
```
---
Language: Proto
BasedOnStyle: Google
ColumnLimit: 0
```

Then `.proto` files can be checked with:

```
clang-format --style=file --Werror ${file}
```

and your checks should be doable with something like:

```bash
if ! clang-format --style=file --Werror ${file}; then
   # handle error case
fi
```


Give it a shot! Ask if anything is unclear and looking forward to seeing the next review. :)

2021-10-01 11:01 UTC, ArthurBandaryk commented on tools/check_style_proto
> +    prototool format -l ${file:2}
Yep, I will omit the first `./`.

2021-10-01 11:01 UTC, ArthurBandaryk commented on tools/check_style_proto
> +      printf "${file:2} file has incorrect code format!\n"
Yes, I will do omit.

2021-10-01 11:15 UTC, ArthurBandaryk commented on tools/check_style_proto
> +    # Check if the specific file has correct code format
I will move it up.

2021-10-01 11:48 UTC, ArthurBandaryk commented
1. Need advise from Ben to choose how we would like to check `.proto` files: using `prototool` or `clang-format`.
2. For now ,as you could remember, `jidicula's clang-format-action` doesn't check if `line[I] > 80` chars. So actually I'm thinking about to remove this action and to base on the Ben's script `tools/pre-commit`. Any thoughts guys?

2021-10-04 14:46 UTC, closed without merging